### ISSUE TITLE
Any chance on bower package?

### ISSUE THREAD

**Issue by telegraphinho** [lolmaus/breakpoint-slicer#13]
Hi, it would be great if this irreplacable plugin could be on bower for those, who don't use compass anymore. Is it possible?

**Comment by lolmaus** [comment]
I can do that, but are you aware that it depends on Breakpoint which depends on Ruby Sass?

**Comment by lolmaus** [comment]
Fixed via f057dcb.

I hope i did it right. Please try it and report any issues.

**Comment by lolmaus** [comment]
By the way, if you use Breakpoint Slicer heavily, join the discussion of how the next major version should behave: #9.
