### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by HankBrown** [lolmaus/breakpoint-slicer#15]
I am sorry to pollute your hub with issues outside the scope of your project.

**The link to singularity now goes to bundler.** I should just submit a pull for the markdown, I trust you understand this is faster for me and such a small change.

What I really wish I kew, is whether it is possible to merge slicer with breakup. I want to use slicer *and* I need to generate separate sheets per breakpoint. Is that a huge endeavour or could I hack it out in half a day...

**Comment by lolmaus** [comment]
Thx. It turned out Bundler and Singularity shared the same footnote. Markdown bug! :D
