### ISSUE TITLE
[Question] Are there any plans for migration to dart-sass?

### ISSUE THREAD

**Issue by alazurenko** [lolmaus/breakpoint-slicer#26]
Dear Maintainer(s),

Are there are any plans for migration to the [state of the art sass](https://sass-lang.com/dart-sass)? 

[FYI](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline)

Warm regards, 
LA

**Comment by lolmaus** [comment]
@alazurenko Breakpoint Slicer did support modern Sass, but relied on globals.

I have rewritten it from scratch, with new convenient API, support for Sass modules, test coverage.

I'm gonna close this are resolved. If you have any issues, please don't hesitate to mention me and I'll reopen.
