### ISSUE TITLE
Slices and media variables cannot be overridden when importing module

### ISSUE THREAD

**Issue by jaradlight** [lolmaus/breakpoint-slicer#27]
Currently, both slices and media variables are not configurable when loading the module. The following will cause an error during compilation:
```scss
@use 'breakpoint-slicer' as bs with ($slices: (small: 0, medium: 400, large: 800));
```
```
SassError: This variable was not declared with !default in the @used module.
13 │ @use 'breakpoint-slicer' as bs with ($slices: (small: 0, medium: 400, large: 800));
   │                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Declaring configurable variables with `!default` allows them to be overridden when loading the module, as described here:
https://sass-lang.com/documentation/at-rules/use#configuration

**Comment by lolmaus** [comment]
Fixed in `3.0.0-beta.0`. Big thanks to @jaradlight for the fix and tests.
