### ISSUE TITLE
FR: Better Standard Default Breakpoint Designations...

### ISSUE THREAD

**Issue by kerns** [lolmaus/breakpoint-slicer#33]
This would correspond better to, for example, tailwind...and most other breakpoint concepts I've seen in the past. 

` xxs   ·   xs   ·    sm    ·    md    ·    lg    ·    xl `

**Comment by lolmaus** [comment]
Hi!

Breakpoint Slices uses T-shirt sizes for slice names, which are IMO very standard and intuitive.

How the names that you propose are better, other than that you personally are used to them?

Please note that you're talking about *slice* names in Breakpoint Slicer, but *breakpoint* names in Tailwind. Those are different concepts, so maybe it's a good thing that they're named differently. :man_shrugging:

**Comment by kerns** [comment]
> Breakpoint Slices uses T-shirt sizes for slice names, which are IMO very standard and intuitive. How the names that you propose are better, other than that you personally are used to them?

I believe I thought they were better for the reason that I was personally more used to them :) But now that you explained your rational I am ready to fully embrace it.

It's also easily changed it seems so if I wanted to map my breakpoints to the sizes and names utilized by tw it would be trivial to do so.

It's a really nice re-write you've done ...so happy you've given this project a new lease on life. Meanwhile, I've successfully integrated a build using both Tailwind's new JIT compiler and Laravel Mix and all the hot reload hotness ... not sure how best to share that here but maybe I can move it into a gist.

**Comment by lolmaus** [comment]
Thanks for the update and for kind words!

I'm glad you've sorted out Sass configuration.

A gist is OK, post a link to the relevant issue.
