### ISSUE TITLE
Support for em-based media queries

### ISSUE THREAD

**Issue by pridyok** [lolmaus/breakpoint-slicer#35]
Currently slices can only be defined in pixels, is there a plan to add support for em-based media queries?

**Comment by lolmaus** [comment]
Hey @pridyok, thank you for your interest in this library!

Breakpoint Slicer supports `px` queries only for a reason. Please read through this discussion:
https://github.com/lolmaus/breakpoint-slicer/issues/30#issuecomment-784032162

You are welcome to comment on that thread.

**Comment by lolmaus** [comment]
Duplicate of #30.
