### ISSUE TITLE
Extending breakpoint-slicer to support vertical media queries

### ISSUE THREAD

**Issue by briangonzalez** [lolmaus/breakpoint-slicer#9]
Just throwing this out there because I would like something like this in one of my current projects.

Would you be open to something like this? If so, what do you think the syntax should look like? I'd be able to help implement.

**Comment by lolmaus** [comment]
Breakpoint Slicer has been rewritten from scratch, it's API simplified and made more convenient.

I've been thinking about vertical media queries and decided not to implement them.

So far, I've only written vertical media queries a few times in my entire career, and I never felt a need for a media query framework to streamline vertical media queries.

On the other side, when there is a real use case for vertical media queries, it's probably gonna be really elaborate. I'm not comfortable with implementing a vertical media query framework without battle-testing it on real, complex cases. I fear the result might not adequately satisfy requirements of such a project, but it would complicate the API for the absolute majority of users.

I am closing this issue to help tracking Breakpoint Slicer problems.

**I welcome everyone who uses vertical media queries to continue the discussion.** I will reopen this thread once it has enough interest. I don't want to modify existing mixins to support vertical media queries, but new mixins could be implemented.
